### ISSUE TITLE
Add double tap+swipe to zoom

### ISSUE THREAD

**Issue by nimra98** [anbraten/opnv-live#17]
The map should support the double tap + swipe (up or down) to zoom out or in as known from the Google Maps app.
Maybe a starting point: [https://stackoverflow.com/questions/3186641/double-tap-zoom-in-googlemaps-activity](url)

**Comment by lukashass** [comment]
FYI this works now. It was implemented in https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.10.0

**Comment by anbraten** [comment]
@lukashass Could you add renovate to this repo, so we can update mapbox?
